export const LANDING_PAGE = "/"
export const LOGIN = "/login"
export const REGISTER = "/register"
export const RECOVER_PASSWORD = "/recover-password"
export const NEW_PASSWORD = "/new-password"
export const EMAIL_NOT_VALIDATED = "/email-validation"
export const EMAIL_VALIDATED = "/email-validated"
export const HOME = "/home"
export const GAME = "/game"
export const PLAYGAME = "/playgame"

export const PROFILE = "/profile"
